### ISSUE TITLE
Duda sobre el ejercicio 3 y  4.

### ISSUE THREAD

**Issue by VlatkoMarchanSekulic** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct10-async-fs-process-alu0101321141.github.io#1]
Hola, buenas tardes.

Mi pregunta sobre el ejercicio 3 se trata sobre el uso de otras funciones de fs aparte del watch, ya que la función watch tan solo nos notifica dos tipos de eventos, _Change_ y _rename_, por lo cual cuando se produce una creación de un archivo  nos mandará un _rename_ y posteriormente un _change_ si se escribe contenido dentro del mismo, eso es un problema ya que al modificar el nombre del archivo, crearlo o eliminarlo solo nos mandará _rename_. Y no podría llegar a distinguirlos de manera correcta. únicamente usando fs.watch.

Por otro lado, en el ejercicio 4, con la clase wrapper no estoy seguro si hay que implementarlo únicamente con procesos de comandos _spawn_ o también se podrían a llegar a utilizar las funcionalidades de __fs__.

Un saludo y buen fin de semana.

**Comment by esegredo** [comment]
Hola Vlatko, buenos días.

En el ejercicio 3, tu puedes llevar un registro de cómo se llama el fichero, por ejemplo, o qué tamaño tiene, desde que lo empiezas a ejecutar. Con esa información, más los dos tipos de eventos, ya podrías saber qué está sucediendo.

En el ejercicio 4, lo ideal es usar solamente `spawn`, dado que es un wrapper de comandos de Unix/Linux.

Si no conseguiste implementar lo anterior podrías hacerlo a lo largo de hoy aunque ya haya pasado la fecha límite.

Saludos.
Eduardo

**Comment by VlatkoMarchanSekulic** [comment]
perfecto, muchas gracias, modificaré el ejercicio 4 para poner _spawn_.
